# Path to vault file with credentials for environment
vault_file:     "/usr/ansible/interview.yml"

# Ansible credentials for docker hosts
ansible_user:     "{{ vault_ansible_user }}"
ansible_password: "{{ vault_ansible_password }}"

# Ansible connection method
ansible_connection:                   winrm
ansible_port:                         5986
ansible_winrm_server_cert_validation: ignore